# Generated by Django 6.0 on 2026-01-04 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_alter_businessuser_options_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='inventorytransaction',
            options={},
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='products.product'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['business', 'product'], name='products_in_busines_177c2c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['business', '-created_at'], name='products_in_busines_13bbab_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['product'], name='products_in_product_729e87_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('business', 'product'), name='unique_inventory_per_business_product'),
        ),
    ]
