# Generated by Django 6.0 on 2026-01-04 08:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessuser',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='businessuser',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='businessuser',
            index=models.Index(fields=['user'], name='businesses__user_id_28a84b_idx'),
        ),
        migrations.AddIndex(
            model_name='businessuser',
            index=models.Index(fields=['business'], name='businesses__busines_35ba40_idx'),
        ),
        migrations.AddConstraint(
            model_name='businessuser',
            constraint=models.UniqueConstraint(fields=('business', 'user'), name='unique_user_per_business'),
        ),
    ]
