# Generated by Django 6.0 on 2026-01-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_alter_businessuser_options_and_more'),
        ('products', '0002_alter_inventory_options_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['business', '-created_at'], name='sales_order_busines_ea4d19_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['business', 'status'], name='sales_order_busines_667f49_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='sales_order_order_i_db59cc_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order'], name='sales_payme_order_i_63f3af_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['paid_at'], name='sales_payme_paid_at_2d9556_idx'),
        ),
    ]
