# Generated by Django 6.0 on 2026-01-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_order_sales_order_busines_ea4d19_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='sales_payme_paid_at_2d9556_idx',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='paid_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='payment',
            name='direction',
            field=models.CharField(choices=[('in', 'Payment'), ('out', 'Refund')], default='in', max_length=5),
        ),
        migrations.AddField(
            model_name='payment',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=10),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='sales_payme_status_402b5d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='sales_payme_created_0df64f_idx'),
        ),
    ]
