# Generated by Django 6.0 on 2026-01-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_alter_businessuser_options_and_more'),
        ('sales', '0003_remove_payment_sales_payme_paid_at_2d9556_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Paid')], db_index=True, default='unpaid', max_length=10),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['business', 'payment_status'], name='sales_order_busines_5d9d75_idx'),
        ),
    ]
