# Generated by Django 6.0 on 2026-01-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_ledgerentry'),
        ('sales', '0004_order_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ledgerentry',
            name='accounts_le_entry_t_dd0637_idx',
        ),
        migrations.RemoveIndex(
            model_name='ledgerentry',
            name='accounts_le_created_9596dd_idx',
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('payment', 'Payment'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('credit', 0), ('debit__gt', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR'), name='ledger_exactly_one_side_positive'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('credit__gte', 0), ('debit__gte', 0)), name='ledger_non_negative_amounts'),
        ),
    ]
