# Generated by Django 6.0 on 2026-01-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_ledgerentry_accounts_le_entry_t_dd0637_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='account_code',
            field=models.CharField(choices=[('AR', 'Accounts Receivable'), ('CASH', 'Cash'), ('REV', 'Revenue'), ('REFUND', 'Refunds')], default='AR', max_length=20),
            preserve_default=False,
        ),
    ]
