# Generated by Django 6.0 on 2026-01-07 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_ledgerentry_account_code"),
    ]


    operations = [
    ]
