# Generated by Django 6.0 on 2026-01-07 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_remove_ledgerentry_account_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='accounts.account'),
            preserve_default=False,
        ),
    ]
