# Generated by Django 6.0 on 2026-01-10 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_ledgerentry_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledgerentry',
            options={'ordering': ['created_at'], 'permissions': [('view_financial_reports', 'Can view financial reports'), ('print_financial_reports', 'Can print financial reports')]},
        ),
    ]
