# Generated by Django 6.0 on 2026-01-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('users_create_user', 'Can create users'), ('users_update_user', 'Can update users'), ('users_disable_user', 'Can disable users'), ('users_assign_roles', 'Can assign roles'), ('users_view_users', 'Can view users'), ('sales_create_order', 'Can create sales orders'), ('sales_update_order', 'Can update sales orders'), ('sales_cancel_order', 'Can cancel sales orders'), ('sales_view_orders', 'Can view sales orders'), ('payments_record_payment', 'Can record payments'), ('payments_refund_payment', 'Can refund payments'), ('payments_view_payments', 'Can view payments'), ('receipts_generate_pdf', 'Can generate receipt PDF'), ('receipts_print_pdf', 'Can print receipt PDF'), ('receipts_print_thermal', 'Can print thermal receipt'), ('receipts_view_receipt', 'Can view receipts'), ('printers_register_printer', 'Can register printers'), ('printers_assign_printer', 'Can assign printers'), ('printers_view_printers', 'Can view printers'), ('reports_view_sales', 'Can view sales reports'), ('reports_view_financials', 'Can view financial reports'), ('audit_view_logs', 'Can view audit logs'), ('audit_view_print_logs', 'Can view receipt print logs'), ('config_update_settings', 'Can update system settings'), ('config_view_settings', 'Can view system settings'), ('system_run_jobs', 'Can run system jobs')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
