# Generated by Django 6.0 on 2026-01-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-created_at'], 'verbose_name': 'Receipt', 'verbose_name_plural': 'Receipts'},
        ),
        migrations.AddField(
            model_name='receipt',
            name='pdf',
            field=models.FileField(blank=True, editable=False, help_text='Generated PDF receipt (immutable)', null=True, upload_to='receipts/pdfs/'),
        ),
    ]
