# Generated by Django 6.0 on 2026-01-13 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_alter_receipt_options_receipt_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='receipt',
            name='pdf',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='receipts/pdfs/'),
        ),
        migrations.CreateModel(
            name='ReceiptPrintLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('pdf', 'PDF'), ('thermal', 'Thermal')], max_length=20)),
                ('printer_name', models.CharField(blank=True, help_text='Optional printer identifier', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('printed_by', models.ForeignKey(blank=True, help_text='User who initiated the print', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_logs', to='receipts.receipt')),
            ],
            options={
                'verbose_name': 'Receipt Print Log',
                'verbose_name_plural': 'Receipt Print Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
